version: '3'
services:
  frontend:
    ports:
      - "8080:80"
    build:
      context: ./
      dockerfile: Dockerfile
  backend:
    ports:
      - "11088:11088"
    build:
      context: ./
      dockerfile: backend.Dockerfile
